# Generated by Django 4.1.5 on 2023-01-27 04:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_dishrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrev',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='dishrev',
            unique_together={('user', 'dish')},
        ),
    ]
